### ISSUE TITLE
Update Linuxdeploy

### ISSUE THREAD

**Issue by rmburg** [tauri-apps/binary-releases#3]
`tauri build` has been broken for a while now on up-to-date Linux systems, as it failed on building the AppImage.
This was caused by an update to glibc breaking Linuxdeploy (https://github.com/linuxdeploy/linuxdeploy/issues/210).
This has just now been fixed in https://github.com/linuxdeploy/linuxdeploy/pull/211 , but the `linuxdeploy` release of this repo still needs to be updated to point to the new artifacts.

CI run of the new version: https://github.com/linuxdeploy/linuxdeploy/actions/runs/2878293346
Fixed AppImage artifact: https://github.com/linuxdeploy/linuxdeploy/suites/7861608611/artifacts/333221700

**Comment by TheAssassin** [comment]
Binary has been published to the release page. Don't rely on those artifacts, they will be removed ultimately. Instead, I recommend to always download from the continuous release page.

**Comment by FabianLars** [comment]
> I recommend to always download from the continuous release page.

That's what we used to do on each `tauri build` call but we started using this repo as a "cache" when we hit https://github.com/linuxdeploy/linuxdeploy/issues/206, and to get older releases we had to use the ci artifacts.

The plan is to upgrade binary-releases to have Tauri specific CI tests and pull new linuxdeploy releases (from the release page) on successful runs :)

**Comment by FabianLars** [comment]
Aaand pinging @lucasfernog because i apparently don't have write access so i can't update the artifacts.

**Comment by rmburg** [comment]
> Binary has been published to the release page. Don't rely on those artifacts, they will be removed ultimately. Instead, I recommend to always download from the continuous release page.

When using the `tauri build` command, it always downloads the artifacts from this repository, afaik there is no easy way to just use the up-to-date artifact.
Relevant code: https://github.com/tauri-apps/tauri/blob/9bbc30590b787be849d122c4f96d9917da2b4181/tooling/bundler/src/bundle/linux/templates/appimage#L73

**Comment by lucasfernog** [comment]
Done.

**Comment by rmburg** [comment]
Can confirm that this fixed `tauri build` for me :tada:
