### ISSUE TITLE
What if the releases can't be download in build process?

### ISSUE THREAD

**Issue by userjia** [tauri-apps/binary-releases#4]
Like:
`Error failed to bundle project: `https://github.com/tauri-apps/binary-releases/releases/download/nsis-3/nsis-3.zip: Network Error: Network Error: Error encountered in the status line:`

Then I try download by hand and extract to C:\Users\user\AppData\Local\tauri, but I get:
`Warn NSIS directory is missing some files. Recreating it. `

And I can't get more steps by searching in internet

**Comment by amrbashir** [comment]
If you were to manually download the files, then you need to download some files manually:
1. Download https://github.com/tauri-apps/binary-releases/releases/download/nsis-3/nsis-3.zip and extract it, then renaming the extracted directory to `NSIS` and move it to `C:\Users\user\AppData\Local\tauri`
2. Download https://github.com/tauri-apps/binary-releases/releases/download/nsis-plugins-v0/NSIS-ApplicationID.zip, extract it and copy `ApplicationID.dll` to `C:\Users\user\AppData\Local\tauri\NSIS\Plugins\x86-unicode`
3. Download the latest `nsis_tauri_utils.dll` from here https://github.com/tauri-apps/nsis-tauri-utils/releases, and copy it to `C:\Users\user\AppData\Local\tauri\NSIS\Plugins\x86-unicode`

The final directory structure should be like this:
```
C:\Users\user\AppData\Local\tauri/
	|_ NSIS/
		|_ makensis.exe
		|_ ... some other files and directories
		|_ Plugins/
			|_ ... some other files and directories
			|_ x86-unicode/
				|_ ... some other files and directories
				|_ ApplicationID.dll
				|_ nsis_tauri_utils.dll
```

**Comment by userjia** [comment]
> If you were to manually download the files, then you need to download some files manually:
> 
>     1. Download https://github.com/tauri-apps/binary-releases/releases/download/nsis-3/nsis-3.zip and extract it, then renaming the extracted directory to `NSIS` and move it to `C:\Users\user\AppData\Local\tauri`
> 
>     2. Download https://github.com/tauri-apps/binary-releases/releases/download/nsis-plugins-v0/NSIS-ApplicationID.zip, extract it and copy `ApplicationID.dll` to `C:\Users\user\AppData\Local\tauri\NSIS\Plugins\x86-unicode`
> 
>     3. Download the latest `nsis_tauri_utils.dll` from here https://github.com/tauri-apps/nsis-tauri-utils/releases, and copy it to `C:\Users\user\AppData\Local\tauri\NSIS\Plugins\x86-unicode`
> 
> 
> The final directory structure should be like this:
> 
> ```
> C:\Users\user\AppData\Local\tauri/
> 	|_ NSIS/
> 		|_ makensis.exe
> 		|_ ... some other files and directories
> 		|_ Plugins/
> 			|_ ... some other files and directories
> 			|_ x86-unicode/
> 				|_ ... some other files and directories
> 				|_ ApplicationID.dll
> 				|_ nsis_tauri_utils.dll
> ```

This works, thank you

**Comment by NowLoadY** [comment]
## Updated Guide for Tauri v2

The original guide is outdated. Key fix: **nsis_tauri_utils.dll must be in additional/ subdirectory**.

### Download Links
- NSIS 3.11: https://github.com/tauri-apps/binary-releases/releases/download/nsis-3.11/nsis-3.11.zip
- ApplicationID: https://github.com/tauri-apps/binary-releases/releases/download/nsis-plugins-v0/NSIS-ApplicationID.zip
- nsis_tauri_utils.dll: https://github.com/tauri-apps/nsis-tauri-utils/releases/latest

### Correct Structure
\\\
%LOCALAPPDATA%\tauri\NSIS\
+-- makensis.exe
+-- Bin\makensis.exe
+-- Plugins\x86-unicode\
|   +-- ApplicationID.dll
|   +-- additional\              <-- CRITICAL!
|       +-- nsis_tauri_utils.dll
+-- ...
\\\

### Steps
1. Extract nsis-3.11.zip, move nsis-3.11 folder to %LOCALAPPDATA%\tauri\NSIS
2. **Create** %LOCALAPPDATA%\tauri\NSIS\Plugins\x86-unicode\additional\
3. Copy nsis_tauri_utils.dll into additional\
4. Copy ApplicationID.dll into x86-unicode\

Reference: [Tauri bundler source](https://github.com/tauri-apps/tauri/blob/dev/crates/tauri-bundler/src/bundle/windows/nsis/mod.rs#L47-L61)
