### ISSUE TITLE
linuxdeploy-aarch64.AppImage is not available

### ISSUE THREAD

**Issue by liudonghua123** [tauri-apps/binary-releases#5]
I tried to build arm64 and armhf target of tauri app on linux, but when it try to build `AppImage`, it failed on downloading https://github.com/tauri-apps/binary-releases/releases/download/linuxdeploy/linuxdeploy-aarch64.AppImage which is not available in https://github.com/tauri-apps/binary-releases/releases/tag/linuxdeploy.

See more details on https://github.com/liudonghua123/pxt-microbit-app/actions/runs/6563010887/job/17826365343#step:11:15055.

**Comment by FabianLars** [comment]
Hey, thanks for the report, this is tracked over here https://github.com/tauri-apps/tauri/issues/4174 - let's keep the conversation in that issue since it's not binary-releases' "fault" that this file doesn't exist :)
